type: minatar
name: Freeway-MinAtar
vmin: ${env.vmin_per_env[${env.name}]}
vmax: ${env.vmax_per_env[${env.name}]}
max_episode_steps: ${env.max_episode_steps_per_env[${env.name}]}

vmax_per_env:
  Freeway-MinAtar: 50
  Asterix-MinAtar: 20
  Breakout-MinAtar: 50
  Seaquest-MinAtar: 50
  SpaceInvaders-MinAtar: 50

vmin_per_env:
  Freeway-MinAtar: 0
  Asterix-MinAtar: 0
  Breakout-MinAtar: 0
  Seaquest-MinAtar: 0
  SpaceInvaders-MinAtar: 0

max_episode_steps_per_env:
  Freeway-MinAtar: 2500
  Asterix-MinAtar: 1000
  Breakout-MinAtar: 1000
  Seaquest-MinAtar: 1000
  SpaceInvaders-MinAtar: 1000