actor:
  _target_: src.algorithms.reppo.networks.SACDiscreteActorNetworks
  _partial_: true
  hidden_dim: ${algorithm.actor_hidden_dim}
  ent_start: ${algorithm.ent_start}
  kl_start: ${algorithm.kl_start}
  use_norm: ${algorithm.use_actor_norm}
  layers: ${algorithm.num_actor_layers}
  min_std: ${algorithm.actor_min_std}
  use_skip: ${algorithm.use_actor_skip}


critic:
  _target_: src.algorithms.reppo.networks.DiscreteCategoricalCriticNetwork
  _partial_: true
  hidden_dim: ${algorithm.critic_hidden_dim}
  use_norm: ${algorithm.use_critic_norm}
  use_simplical_embedding: false
  encoder_layers: ${algorithm.num_critic_encoder_layers}
  head_layers: ${algorithm.num_critic_head_layers}
  pred_layers: ${algorithm.num_critic_pred_layers}
  num_bins: ${algorithm.num_bins}
  vmin: ${env.vmin}
  vmax: ${env.vmax}
  use_skip: ${algorithm.use_critic_skip}
